In [1]:
import pandas as pd

df1 = pd.read_excel('KIDB-export-29457ae0-8a89-4b0a-a8d7-f0a940ea3ffb.xlsx')
df2 = pd.read_excel('KIDB-export-d7648f85-207a-4459-b61e-6740ffc9bba2.xlsx')
df1.head()

,Economy,Indicator,Unit of Measure,2000,2001,2002,2003,2004,2005,2006,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"Taipei,China","Domestic Material Consumption, All (t million)",metric ton,3.004831e+08,3.073673e+08,3.129428e+08,3.085902e+08,3.281805e+08,3.334417e+08,3.305002e+08,...,3.047043e+08,2.896603e+08,2.766103e+08,2.770446e+08,2.800146e+08,2.767025e+08,...,...,...,...
1,Afghanistan,"Domestic Material Consumption, All (t million)",metric ton,2.435790e+07,2.336741e+07,2.999081e+07,3.197478e+07,3.000812e+07,3.548501e+07,3.341325e+07,...,5.068024e+07,4.994508e+07,5.024937e+07,4.527223e+07,4.704707e+07,4.656412e+07,...,...,...,...
2,Armenia,"Domestic Material Consumption, All (t million)",metric ton,2.846344e+07,2.938279e+07,3.154986e+07,3.163958e+07,3.582363e+07,3.713392e+07,3.859969e+07,...,3.986121e+07,4.062453e+07,5.199482e+07,5.282901e+07,4.729654e+07,4.930680e+07,...,...,...,...
3,Azerbaijan,"Domestic Material Consumption, All (t million)",metric ton,3.238712e+07,3.414138e+07,3.942543e+07,4.439560e+07,5.203480e+07,6.023851e+07,6.675132e+07,...,9.808647e+07,8.129447e+07,7.829364e+07,8.533137e+07,9.337336e+07,9.604044e+07,...,...,...,...
4,Georgia,"Domestic Material Consumption, All (t million)",metric ton,1.516442e+07,1.659733e+07,1.815217e+07,1.889491e+07,1.912233e+07,2.092677e+07,1.998464e+07,...,3.188510e+07,3.680079e+07,3.934212e+07,4.165542e+07,4.325274e+07,4.511500e+07,...,...,...,...

In [7]:
df2= df2.iloc[:,:23]

# Melt the DataFrame
melted_df = pd.melt(df2, id_vars=['Economy', 'Indicator', 'Unit of Measure'], var_name='Year', value_name='Value')

# Optionally, you can convert the 'Year' column to numeric if needed
melted_df['Year'] = pd.to_numeric(melted_df['Year'], errors='coerce')

# Save the melted DataFrame to a new file
melted_df.to_csv('melted_dataset2.csv', index=False)

In [6]:
import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd
from dash import Output, Input

# Assuming 'melted_dataset.csv' is the file generated in the previous step
df = melted_df.copy()

# Initialize the Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Domestic Material Consumption by Year and Country"),
    
    dcc.Dropdown(
        id='country-dropdown',
        options=[{'label': country, 'value': country} for country in df['Economy'].unique()],
        value=df['Economy'].iloc[0],
        multi=False,
        style={'width': '50%'}
    ),
    
    dcc.Graph(id='line-chart'),
])

# Callback to update the line chart based on the selected country
@app.callback(
    Output('line-chart', 'figure'),
    [Input('country-dropdown', 'value')]
)
def update_chart(selected_country):
    filtered_df = df[df['Economy'] == selected_country]
    fig = px.line(filtered_df, x='Year', y='Value', title=f'Domestic Material Consumption for {selected_country}')
    return fig

# Run the app in the notebook
app.run_server(debug=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__'
 * Debug mode: off